# Generated by Django 3.1.3 on 2020-11-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catalog_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='№ каталога'),
        ),
        migrations.AlterField(
            model_name='products',
            name='edizm',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Ед.изм'),
        ),
        migrations.AlterField(
            model_name='products',
            name='number',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Ценник'),
        ),
        migrations.AlterField(
            model_name='products',
            name='ostatok',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Остаток'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Наименование'),
        ),
    ]
