# Generated by Django 3.1.3 on 2020-11-22 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0002_auto_20201121_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
