# Generated by Django 3.1.3 on 2020-11-22 15:05

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sto', '0003_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': 'Сервис ПАЗ',
                'verbose_name_plural': 'Сервисы ПАЗ',
            },
        ),
    ]
